"""Check test coverage against configurable thresholds.

Validates that code coverage meets the required threshold by parsing Cobertura
XML reports (generated by ``pytest-cov``). Supports per-module thresholds via
a ``coverage.toml`` config file.

Usage::

    hephaestus-check-coverage --path src/ --coverage-file coverage.xml
    hephaestus-check-coverage --threshold 80 --path mypackage/
    hephaestus-check-coverage --config coverage.toml --verbose
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, cast

from hephaestus.utils.helpers import get_repo_root

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]


def load_coverage_config(config_file: Path | None = None) -> dict[str, Any]:
    """Load coverage configuration from ``coverage.toml``.

    Args:
        config_file: Path to ``coverage.toml``. If None, looks for
            ``coverage.toml`` in the repo root.

    Returns:
        Dictionary with coverage configuration. Returns defaults if
        file not found.

    """
    if config_file is None:
        try:
            repo_root = get_repo_root()
            config_file = repo_root / "coverage.toml"
        except (FileNotFoundError, RuntimeError):
            return _default_config()

    if not config_file.exists():
        return _default_config()

    if tomllib is None:
        print(
            "WARNING: tomllib/tomli not available, using default coverage config",
            file=sys.stderr,
        )
        return _default_config()

    try:
        with open(config_file, "rb") as f:
            config = tomllib.load(f)
        return cast(dict[Any, Any], config)
    except Exception as e:
        print(
            f"WARNING: Failed to load config from {config_file}: {e}",
            file=sys.stderr,
        )
        return _default_config()


def _default_config() -> dict[str, Any]:
    """Return the default coverage configuration."""
    return {"coverage": {"target": 90.0, "minimum": 80.0}}


def get_module_threshold(path: str, config: dict[str, Any]) -> float:
    """Get coverage threshold for a specific module.

    Tries an exact path match first, then prefix match, then falls back
    to the overall minimum threshold.

    Args:
        path: Module path (e.g. ``"mypackage/core"``).
        config: Configuration dictionary from :func:`load_coverage_config`.

    Returns:
        Minimum coverage threshold for the module.

    """
    modules = config.get("coverage", {}).get("modules", {})

    if path in modules:
        return cast(float, modules[path].get("minimum", 90.0))

    for module_path in sorted(modules.keys(), key=len, reverse=True):
        if path.startswith(module_path):
            return cast(float, modules[module_path].get("minimum", 90.0))

    return cast(float, config.get("coverage", {}).get("minimum", 80.0))


def parse_coverage_report(coverage_file: Path) -> float | None:
    """Parse a Cobertura XML coverage report and extract total coverage.

    Args:
        coverage_file: Path to ``coverage.xml`` file.

    Returns:
        Coverage percentage (0-100), or None if file not found or invalid.

    """
    if not coverage_file.exists():
        print(f"Coverage file not found: {coverage_file}", file=sys.stderr)
        return None

    try:
        import defusedxml.ElementTree as ET
    except ImportError:
        print(
            "WARNING: defusedxml not installed. "
            "Install with: pip install HomericIntelligence-Hephaestus[xml]",
            file=sys.stderr,
        )
        return None

    try:
        tree = ET.parse(str(coverage_file))
        root = tree.getroot()
        line_rate = root.get("line-rate")
        if line_rate is not None:
            return float(line_rate) * 100.0
        print(f"Warning: No line-rate found in {coverage_file}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"Error parsing coverage file: {e}", file=sys.stderr)
        return None


def check_coverage(threshold: float, path: str, coverage_file: Path) -> bool:
    """Check if coverage meets threshold.

    Args:
        threshold: Minimum required coverage percentage.
        path: Path to source code being tested (for display).
        coverage_file: Path to coverage report.

    Returns:
        True if coverage meets threshold or coverage is not available,
        False only if coverage parsing succeeds but is below threshold.

    """
    coverage = parse_coverage_report(coverage_file)

    if coverage is None:
        print(f"\nCoverage Report: {path}")
        print("  Status: Coverage data not available")
        print("  PASSED - Coverage check skipped")
        return True

    print(f"\nCoverage Report: {path}")
    print(f"  Coverage: {coverage:.2f}%")
    print(f"  Threshold: {threshold:.2f}%")

    if coverage >= threshold:
        print("  PASSED - Coverage meets threshold")
        return True

    gap = threshold - coverage
    print(f"  FAILED - Coverage is {gap:.2f}% below threshold")
    return False


def main() -> int:
    """CLI entry point for coverage checking.

    Returns:
        Exit code (0 if coverage meets threshold, 1 otherwise).

    """
    parser = argparse.ArgumentParser(
        description="Check test coverage against threshold",
        epilog="Example: %(prog)s --threshold 80 --path mypackage/",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Minimum required coverage percentage (overrides config)",
    )
    parser.add_argument(
        "--path",
        type=str,
        default=".",
        help="Path to source code being tested (default: .)",
    )
    parser.add_argument(
        "--coverage-file",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage report file (default: coverage.xml)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to coverage.toml config file",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose output",
    )

    args = parser.parse_args()

    config = load_coverage_config(args.config)

    if args.threshold is not None:
        threshold = args.threshold
    else:
        threshold = get_module_threshold(args.path, config)

    if args.verbose:
        print("Checking coverage with settings:")
        print(f"  Threshold: {threshold}%")
        print(f"  Path: {args.path}")
        print(f"  Coverage file: {args.coverage_file}")

    if not args.coverage_file.exists():
        print(f"\nWARNING: Coverage file not found: {args.coverage_file}", file=sys.stderr)
        print(
            "\nRun tests with coverage first: pytest --cov=<package> --cov-report=xml",
            file=sys.stderr,
        )
        return 1

    success = check_coverage(threshold, args.path, args.coverage_file)
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
