"""Compatibility wrapper for shared Git helpers.

The canonical implementations live in :mod:`hephaestus.utils.git` so library
packages such as :mod:`hephaestus.github` can use them without importing the
automation product layer.
"""

from hephaestus.utils.git import (
    _remove_untracked_files_tracked_by_ref as _remove_untracked_files_tracked_by_ref,
    clean_stale_git_locks as clean_stale_git_locks,
    clear_repo_caches as clear_repo_caches,
    get_current_branch as get_current_branch,
    get_repo_info as get_repo_info,
    get_repo_root as get_repo_root,
    get_repo_slug as get_repo_slug,
    git_branch_exists as git_branch_exists,
    git_config_get as git_config_get,
    git_diff_unmerged_names as git_diff_unmerged_names,
    git_fetch as git_fetch,
    git_ls_remote as git_ls_remote,
    git_push as git_push,
    git_rebase as git_rebase,
    git_remote_url as git_remote_url,
    git_rev_list_count as git_rev_list_count,
    git_rev_parse as git_rev_parse,
    git_show_toplevel as git_show_toplevel,
    git_status_porcelain as git_status_porcelain,
    is_clean_working_tree as is_clean_working_tree,
    issue_ref as issue_ref,
    pr_ref as pr_ref,
    push_current_branch_with_lease_on_divergence as push_current_branch_with_lease_on_divergence,
    rebase_worktree_onto as rebase_worktree_onto,
    run as run,
    run_git as run_git,
    safe_git_fetch as safe_git_fetch,
    sync_worktree_to_remote_branch as sync_worktree_to_remote_branch,
)

__all__ = [
    "clean_stale_git_locks",
    "clear_repo_caches",
    "get_current_branch",
    "get_repo_info",
    "get_repo_root",
    "get_repo_slug",
    "git_branch_exists",
    "git_config_get",
    "git_diff_unmerged_names",
    "git_fetch",
    "git_ls_remote",
    "git_push",
    "git_rebase",
    "git_remote_url",
    "git_rev_list_count",
    "git_rev_parse",
    "git_show_toplevel",
    "git_status_porcelain",
    "is_clean_working_tree",
    "issue_ref",
    "pr_ref",
    "push_current_branch_with_lease_on_divergence",
    "rebase_worktree_onto",
    "run",
    "run_git",
    "safe_git_fetch",
    "sync_worktree_to_remote_branch",
]
